spring.application.name=CART-ORDER-SERVICE
server.port=${SERVER_PORT:8084}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cart_order_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:9078}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
services.product.base-url=${PRODUCT_SERVICE_URL:http://localhost:8080}
services.inventory.base-url=${INVENTORY_SERVICE_URL:http://localhost:8081}
